[module]
[[module.mounts]]
# Workaround for https://github.com/gohugoio/hugo/issues/6945
source = "assets/scss/bootstrap/_vendor"
target = "assets/scss/bootstrap/vendor"
[[module.imports]]
path="github.com/twbs/bootstrap"
[[module.imports.mounts]]
source = "scss"
target = "assets/scss/bootstrap"